=== oscarjb1/GenericFlowControlEnginne/src/main/resources/META-INF/FlowControls.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.pr.americas.com/genericFlowControl/config">
  <xs:element name="FlowControls">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="FlowControl" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
              <xs:element name="Converter">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="name" use="optional"/>
                      <xs:attribute type="xs:string" name="class" use="optional"/>
                      <xs:attribute type="xs:string" name="inputVar" use="optional"/>
                      <xs:attribute type="xs:string" name="outputVar" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="RestCall">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="name" use="optional"/>
                      <xs:attribute type="xs:string" name="method" use="optional"/>
                      <xs:attribute type="xs:string" name="url" use="optional"/>
                      <xs:attribute type="xs:string" name="input" use="optional"/>
                      <xs:attribute type="xs:string" name="output" use="optional"/>
                      <xs:attribute type="xs:string" name="class" use="optional"/>
                      <xs:attribute type="xs:string" name="outputVar" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="Response">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="responseVar" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:choice>
            <xs:attribute type="xs:string" name="name" use="optional"/>
            <xs:attribute type="xs:string" name="discriminator" use="optional"/>
            <xs:attribute type="xs:string" name="complexDiscriminatorClass" use="optional"/>
            <xs:attribute type="xs:string" name="cannonicalConverterClass" use="optional"/>
            <xs:attribute type="xs:string" name="flowClass" use="optional"/>
            <xs:attribute type="xs:string" name="inputType" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== oscarjb1/GenericFlowControlEnginne/src/main/resources/META-INF/FlowControls.xml
<?xml version="1.0" encoding="UTF-8"?>
<FlowControls xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://xmlns.pr.americas.com/genericFlowControl/config" xsi:schemaLocation="http://xmlns.pr.americas.com/genericFlowControl/config FlowControls.xsd">
	<FlowControl name="xmlCurrency" discriminator="CurrenciRequest" complexDiscriminatorClass="" cannonicalConverterClass="com.pr.gfce.converter.impl.XMLExchangeCannonical" inputType="xml">
            <Converter name="parseRequest" class="com.pr.gfce.converter.impl.FixerRequestConverter" inputVar="payload" outputVar="exchangeRequest"/>
            <RestCall name="ExchangeAPI" method="GET" url="http://api.fixer.io/latest?symbols=USD,GBP" input="exchangeRequest" output="exchangeResponse"/>
            <Converter name="parseResponse" class="com.pr.gfce.converter.impl.FirexResponseConverter" inputVar="exchangeResponse" outputVar="response"/>
            <Response responseVar="response"/>
        </FlowControl>
        <FlowControl name="jsonCurrency" discriminator="pair" complexDiscriminatorClass="" cannonicalConverterClass="com.pr.gfce.converter.impl.JSONExchangeCannonical" inputType="json">
            <Converter name="parseRequest" class="com.pr.gfce.converter.impl.FixerRequestConverter" inputVar="payload" outputVar="exchangeRequest"/>
            <RestCall name="ExchangeAPI" method="GET" url="http://api.fixer.io/latest?symbols=USD,GBP" input="exchangeRequest" output="exchangeResponse"/>
            <Converter name="parseResponse" class="com.pr.gfce.converter.impl.FirexResponseConverter" inputVar="exchangeResponse" outputVar="response"/>
            <Response responseVar="response"/>
        </FlowControl>
</FlowControls>
